num_traj: 0

use_planner: true

MPC:
  N: 100
  dt: 0.1
  SQP_iters: 2
  stateScaling: [1, 1, 1, 1]
  inputScaling: [.1, .1]
  terminalScaling: 50
  tau_max: 5
  vel_max: 0.2
  path_length_cost: 10
  use_previous_reference: true

Planner:
  bez_dt: 0.5
  buffer: 0.1
  num_points: 4000
  x_bounds: [-3, 3, -1.5, 1.5] # min_x, max_x, min_y, max_y
  dx_bounds: [0, 0, 0, 0] # min_dx, max_dx, min_dy, max_dy
  log_edges: false
