num_traj: 0

use_planner: true

MPC:
  N: 100
  dt: 0.05
  SQP_iters: 1
  stateRefScaling: [10, 10, 0, 0]
  stateGoalScaling: [1, 1, 0, 0]
  path_length_cost: [10, 10, 10, 10]
  terminalScaling: [1, 1, 1, 1]
  inputScaling: [.1, .1]
  tau_max: 5
  vel_max: 0.2

Planner:
  bez_dt: 0.75
  buffer: 0.08
  x_bounds: [-5, 5, -5, 5] # min_x, max_x, min_y, max_y
  # bez_dt: 0.5
  # x_bounds: [-2.5, 2.5, -1.5, 1.5] # min_x, max_x, min_y, max_y
  dx_bounds: [0, 0, 0, 0] # min_dx, max_dx, min_dy, max_dy
  log_edges: false
  use_zed: false
  use_random_grid: false
  num_points: 4000
  # use_random_grid: true
  # num_points: 4000
