num_traj: 0

MPC:
  N: 10
  dt: 1.0
  SQP_iters: 2
  buffer: 0.2
  stateScaling: [1, 1, 10, 10]
  inputScaling: [10, 10]
  terminalScaling: 10
  tau_max: 5
  use_previous_reference: false

Planner:
  num_points: 600
  x_bounds: [-2, 2, -1.5, 1.5] # min_x, max_x, min_y, max_y
  dx_bounds: [0, 0, 0, 0] # min_dx, max_dx, min_dy, max_dy
  log_edges: false